### ISSUE TITLE
There is no way to set coroutine context to Deferred

### ISSUE THREAD

**Issue by adjorno** [JakeWharton/retrofit2-kotlin-coroutines-adapter#11]

**Comment by JakeWharton** [comment]
The request is executed asynchronously on OkHttp's dispatcher threads and not in any coroutine context. This allows http/2 optimizations by sharing threads internally in a manner similar to coroutines but it's entirely internal and an implementation detail of OkHttp. If you want to control the context on which your coroutine resumes you can do that through normal means, but we won't be providing a mechanism for controlling where the request happens because it would actually be more wasteful than what's already happening.

**Comment by adjorno** [comment]
Thanks for the answer. The problem in my case is I am not the owner of okhttpclient object, it's created by third-party library and I can't set a custom dispatcher.
