### ISSUE TITLE
[Question] Coroutine cancellation is not handled, right?

### ISSUE THREAD

**Issue by LouisCAD** [JakeWharton/retrofit2-kotlin-coroutines-adapter#7]
The coroutineContext is not shared with the calling coroutine, right?
Did anyone find a way to wrap these calls so `cancel()` is called on the returned `Deferred` instance if the calling coroutine is cancelled?

Also, @JakeWharton, I remember you talking about an idea on how to directly support `suspend` functions in Retrofit in a Tweet. Would it handle cancellation and cancel any in progress request?

**Comment by LouisCAD** [comment]
Oh, it seems it's already WIP in [the jakew/suspend/2018-02-16 branch](https://github.com/JakeWharton/retrofit2-kotlin-coroutines-adapter/tree/jakew/suspend/2018-02-16), using Retrofit 2.4.0 (SNAPSHOT in the WIP latest commit), and it seems it'd handle cancellation thanks to the `coroutineContext` property in the `Continuation` interface!

**Comment by vadymhimself** [comment]
@LouisCAD can you give a usage example?

**Comment by LouisCAD** [comment]
@bolein Cancellation support is first class in Kotlin coroutines.
See docs:
- https://github.com/Kotlin/kotlinx.coroutines/blob/master/coroutines-guide.md#cancellation-and-timeouts
- https://github.com/Kotlin/kotlinx.coroutines/blob/master/ui/coroutines-guide-ui.md#cancel-ui-coroutine

**Comment by vadymhimself** [comment]
@LouisCAD I asked for an example usage of the CallbackAdapter in jakew/suspend/2018-02-16 branch. I don't really understand the purpose of CallbackAdapters and how it is meant to support cancellations.

**Comment by LouisCAD** [comment]
@bolein The `Continuation` interface of Kotlin coroutines allows chaining callbacks, minimizing runnable instances allocation, by using a state machine, but the current version of Retrofit is not compatible. The suspend prototype allows to write adapters that work on `Continuation` or alike concepts.

Without this, the best you can get in regards to coroutines support is what is in this library: https://github.com/gildor/kotlin-coroutines-retrofit

**Comment by vadymhimself** [comment]
@LouisCAD that is still not quite what I asked.

However, I found an answer myself and feel responsible to share it with anyone interested.

This repository contains an adapter that enables the use of coroutines with Retrofit methods. The master branch contains a simple `CallAdapter` that converts the original Retrofit's `Call<T>` into a `Deferred<T>`, a so-called "non-blocking future". The `await` method must be called on a `Deferred` object in order for the function to be suspended.

Usage example: 
```Kotlin
@GET("weather")
fun getWeather() : Deferred<WeatherResponse>
```

There is another way of executing Retrofit requests by using a `Callback<T>`. This callback must be the last parameter in the method.

```Kotlin
@GET("weather")
fun getWeather(callback : Callback<WeatherResponse>)
```
This approach to execution is limited, because it does not provide a way to cancel the request. However, this approach has something in common with the implementation of suspending functions on JVM.

```Kotlin
@GET("weather")
suspend fun getWeather() : WeatherResponse
```
It turns out, that functions marked as `suspend` in Kotlin are compiled into JVM methods that use a sort of callbacks themselves to return the execution after completion or error. Previous Kotlin method will compile into this equivalent in Java:
```Java
@GET("weather")
@Nullable
Object getWeather(@NotNull Continuation<WeatherResponse> var1);
```

`Continuation` can be viewed as a callback that will be used by suspending function. So what @JakeWharton did by introducing `CallbackAdapter`s is a way to use the `Continuation<T>` to deliver the result of the request the way we would do it with a `Callback<T>`. 

This allows us to mark Retrofit methods as suspending functions and never explicitly `await` them. In addition, as @LouisCAD pointed out, such approach has an important advantage over the regular `Callback<T>`: it supports [cancellation](https://github.com/Kotlin/kotlinx.coroutines/blob/master/ui/coroutines-guide-ui.md#cancel-ui-coroutine).

@JakeWharton please correct me if I got anything wrong.

**Comment by vadymhimself** [comment]
Currently, I can't find any signs of the cancellation support. @JakeWharton what is the status of this feature? I believe that there is no way to be notified of the Job cancellation through the `Continuation` interface at this moment.

**Comment by matejdro** [comment]
Don't [these `invokeOnCompletion` calls](https://github.com/JakeWharton/retrofit2-kotlin-coroutines-adapter/blob/d41c3198a3e909041d7245683b3cc9bc230dd8f6/src/main/java/com/jakewharton/retrofit2/adapter/kotlin/coroutines/CoroutineCallAdapterFactory.kt#L91) handle cancellation?

**Comment by LouisCAD** [comment]
They should, but since no CoroutineContext is passed, and since there's no
suspension point in the API interface methods where it could be retrieved
from the continuation, there's no way to cancel in practice.

**Comment by matejdro** [comment]
Doesn't context get passed when you call `await()` method?

**Comment by LouisCAD** [comment]
No because the coroutine that originated the call is already launched in
another CoroutineContext that you don't control, and if you parallelize
requests, awaiting for `await()` calls to make it cancellable would be too
late anyway.

**Comment by hrach** [comment]
This seems like a pretty serious issue. Now when coroutines getting non-experimental it would be great to continue with the work and get CallbackAdapter to (stable) retrotif (release) to allow proper implementation for suspend and also include this lib into the retrofit itself eventually.

**Comment by JakeWharton** [comment]
Won't fix.

https://github.com/square/retrofit/pull/2886

**Comment by michaldrabik** [comment]
I'm sorry for digging this up but as for today does it mean that Retrofit and Coroutines are unusable?

Basically if I start a network call with a coroutine and cancel it when its ongoing (AAC ViewModel is being cleared) the app crashes with an uncaught exception from the CallAdapter.

Anything I can do or just wait for the first-hand suspend support release? Cheers
